# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BiddingSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBAudienceNetwork', '4.26.0'
end
