# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fan_banner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBAudienceNetwork'

  target 'fan_bannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fan_bannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
