# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMobWrapper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdMobWrapper
  pod 'FBAudienceNetwork'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationFacebook'
end
